version: '3.8'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DB: ${MONGO_DB}
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongodb:/data/db
    networks:
      - apps

  minio:
    image: 'bitnami/minio:latest'
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./volumes/minio:/data

networks:
  apps: